CREATE DATABASE CAPSTONE_2024;
USE CAPSTONE_2024;
/*
DROP TABLE IF EXISTS USER_AUTHENTICATION;
DROP TABLE IF EXISTS MATCH_INFO;
DROP TABLE IF EXISTS TEAM_INFO;
DROP TABLE IF EXISTS LEAGUE_INFO;
DROP TABLE IF EXISTS USER_INFO;
DROP TABLE IF EXISTS COUNTRY_CITIES2;
DROP TABLE IF EXISTS BREAK_TEAM_INFO;
*/
CREATE TABLE USER_INFO (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(50),
    USER_SURNAME VARCHAR(50),
    USER_PHONE VARCHAR(16),
    USER_EMAIL VARCHAR(100) UNIQUE NOT NULL
);
CREATE TABLE USER_AUTHENTICATION (
    AUTH_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    USERPASS VARCHAR(255) NOT NULL,
    FOREIGN KEY (USER_ID)  REFERENCES USER_INFO (USER_ID)
);
CREATE TABLE LEAGUE_INFO (
    LEAGUE_ID INT PRIMARY KEY AUTO_INCREMENT,
    LEAGUE_NAME VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(60),
    TEAM_COUNT INT NOT NULL,
    USER_ID INT,
    FOREIGN KEY (USER_ID)  REFERENCES USER_INFO (USER_ID)
);
CREATE TABLE TEAM_INFO (
    TEAM_ID INT PRIMARY KEY AUTO_INCREMENT,
    TEAM_NAME VARCHAR(100),
    CITY VARCHAR(50),
    TEAM_VALUE VARCHAR(50),
    LEAGUE_ID INT NOT NULL,
    FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE_INFO (LEAGUE_ID)
);
-- CREATE A TRIGGER TO SET THE DEFAULT VALUE BASED ON TEAM_ID
DELIMITER //
CREATE TRIGGER SETDEFAULTTEAMNAME
BEFORE INSERT ON TEAM_INFO
FOR EACH ROW
BEGIN
    IF NEW.TEAM_NAME IS NULL OR NEW.TEAM_NAME = '' THEN
        SET NEW.TEAM_NAME = CONCAT('TEAM ', NEW.TEAM_ID); -- EX. TEAM 36
    END IF;
END;
//
DELIMITER ;
CREATE TABLE MATCH_INFO (
    MATCH_ID INT PRIMARY KEY AUTO_INCREMENT,
    LEAGUE_ID INT,
    HOMETEAM_ID INT NOT NULL,
    AWAYTEAM_ID INT NOT NULL,
    MATCH_WEEK INT NOT NULL,
    FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE_INFO(LEAGUE_ID),
    FOREIGN KEY (HOMETEAM_ID) REFERENCES TEAM_INFO(TEAM_ID),
    FOREIGN KEY (AWAYTEAM_ID) REFERENCES TEAM_INFO(TEAM_ID)
);
CREATE TABLE COUNTRY_CITIES (
	lat DECIMAL(20,2),
	lng DECIMAL(20,2),
	country	VARCHAR(60),
	city VARCHAR(60)
);
CREATE TABLE BREAK_TEAM_INFO (
	LEAGUE_ID INT,
	TEAM_ID INT,
	WEEK_INFO INT
);
